config/routes.rb
Spree::Core::Engine.routes.draw do
  post "/printful/webhook", to: "printful#webhook", as: :printful_webhook
  namespace :admin, path: Spree.admin_path do
    resource  :printful_settings, only: [:edit, :update]
  end
end

app/controllers/spree/admin/printful_settings_controller.rb
class Spree::Admin::PrintfulSettingsController < Spree::Admin::BaseController

  def edit
    @preferences_GeneralSettings = [[:printful_api_key, :string], [:printful_gift_subject, :string], [:printful_gift_message, :text]]
    @preferences_WebhookSettings = [[:printful_webhook_username, :string], [:printful_webhook_password, :password]]
  end

  def update
    params['printful_webhook_password'] ||= params['printful_webhook_username']
    params.each do |name, value|
      next unless Spree::Config.has_preference? name
      Spree::Config[name] = value
    end

    begin
      pf = PrintfulClient.new(Spree::Config.printful_api_key)
      pp = pf.post('webhooks', {url: printful_webhook_url(printful_webhook_username:Spree::Config[:printful_webhook_username], printful_webhook_password: Spree::Config[:printful_webhook_password]), types: ['package_shipped', 'order_failed', 'order_canceled']})
      flash[:success] = Spree.t(:successfully_updated, resource: Spree.t(:printful_settings))
    rescue PrintfulApiException, PrintfulException, URI::InvalidURIError => e
      puts 'Printful exception: ' + e.message #Error while doing the request
      flash[:error] = Spree.t(:error_occured, resource: Spree.t(:printful_settings))
    end

    redirect_to edit_admin_printful_settings_path
  end
end

app/views/spree/admin/printful_settings/_form.html.erb
<div data-hook="admin_printful_settings_form_fields">
  <div class="row">
    <div class="col-md-6">
      <fieldset>
        <legend><%= Spree.t(:general) %></legend>
        <% @preferences_GeneralSettings.each do |key| %>
          <div class="form-group">
            <div class="field">
              <%= label_tag key.first %>
              <%= preference_field_tag(key.first, Spree::Config[key.first], type: key.last) %>
            </div>
          </div>
        <% end %>
      </fieldset>
    </div>
    <div class="col-md-6">
      <fieldset>
        <legend><%= t('spree_printful.printful_webhook') %></legend>
        <% @preferences_WebhookSettings.each do |key| %>
          <div class="form-group">
            <div class="field">
              <%= label_tag key.first %>
              <%= preference_field_tag(key.first, Spree::Config[key.first], type: key.last) %>
            </div>
          </div>
        <% end %>
      </fieldset>
    </div>
  </div>
</div>

app/views/spree/admin/printful_settings/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:printful_settings) %>
<% end %>

<%= form_tag admin_printful_settings_path, method: :put do |f| %>
  <%= render 'form', f: f %>
  <div class="form-actions actions" data-hook="buttons"><%= button Spree.t('actions.update'), 'update' %></div>
<% end %>